### ISSUE TITLE
Shiny Pokemon Not Always Detected by Event Handler

### ISSUE THREAD

**Issue by MastaC729** [xPXpanD/PixelmonBroadcasts#1] opened 2018-10-22 01:17 UTC
On our server we have noticed that occasionally shiny spawns will not broadcast to the chat. It only seems to happen intermittently, but I've noticed it happens 100% of the time when I spawn it in with /pokespawn or if it was spawned by fishing. Our server also has a number of other Sponge plugins running on it, and tps has been somewhat bad at times just to give a bit more context.

**Versions**
 - Pixelmon Broadcasts version: 0.2.2
 - Pixelmon version: 6.3.4
 - Forge version: 2705
 - SpongeForge version: 3481

Let me know if I am missing any pertinent information.

**Comment by xPXpanD** [comment] 2018-10-22 09:29
Commands are known, as they don't fire the right events -- I might be able to work around that eventually, but for now support for that is on the back burner. Fishing is interesting, though. I'll have to look into that for the upcoming 0.2.3 release. Hopefully there's an event there that I can intercept as well.

I've also had one other report of normal spawns occasionally not showing up, though I'm not too sure what could cause that yet. I haven't been able to reproduce it in testing yet, either.

For now... Do you use any plugins or sidemods that could also be listening for Pokémon spawns? If so, which ones, and what versions? Might be able to narrow things down a little with multiple mod lists.

Thanks for the report.

**Comment by MastaC729** [comment] 2018-10-23 03:53
After testing it on my private server running only LuckPerms and GriefPrevention as the only other plugins, it appears that every shiny that naturally spawns is broadcasting properly. So it very well could be one of these plugins we have installed on our server that is causing the issue.

Here are the plugins we have installed:

```
FastAsyncWorldEdit
Nucleus
ArmorStandTools
Holograms
LuckPerms
GriefPrevention
UltimateChat
EMPSponge
MCClans
Punish
EconomyLite
TeslaCrate
PlayerShopsRPG
PixelExtras
AdamantineShield
TeslaPowered
Gameshark
DailyRewardsExtended
PixelBuilt-Quests
PlayerGrow
SlotMachines
AutoBroadcaster
WonderTrade
TrainerItem
PokeExpMultiplier
PokeDisguise
TabModifier
PixelmonEconomyBridge
PokeDisplay
```

I know not all of these are related to Pixelmon, but I posted them just in case you may think they are affecting your plugin somehow.

**Comment by xPXpanD** [comment] 2018-10-23 09:06
Thanks for the list. I don't see anything there that I'd expect to cause any issues (except for maybe PokéDisguise? not sure how that spawns stuff), but I'll keep an eye out. 

To anybody else reading this with the same issue: please add your mod/plugin list as well! Would be nice to get this pinned down.

**Comment by xPXpanD** [comment] 2019-05-13 13:34
Closing due to age!

**Closed as completed by xPXpanD** 2019-05-13 13:34 UTC
